### ISSUE TITLE
jiri profile error

### ISSUE THREAD

**Issue by ghost** [vanadium/issues#914]
Several tests are now producing errors like this:

11:15:09 ##### Running test "vanadium-go-race" #####
11:15:09 hostname = "jenkins-node60"
11:15:09 workdir = "/home/veyron/tmp/vanadium-go-race/491267995"
11:15:09 bin dir = "/home/veyron/tmp/vanadium-go-race/491267995/bin"
11:15:09 cleanupProfiles: commands: [cleanup --ensure-specific-versions-are-set --gc]
11:15:09 cleanupProfiles: remove: []
11:15:09 jiri v23-profile list: <nil> [[
11:15:09 base amd64-linux@1 
11:15:09 go amd64-linux@1.5.1 
11:15:09 syncbase amd64-linux@1 
11:15:09 ]]
11:15:09 jiri v23-profile cleanup --ensure-specific-versions-are-set --gc: <nil> [[
11:15:09 ]]
11:15:09 jiri v23-profile list: <nil> [[
11:15:09 base amd64-linux@1 
11:15:09 go amd64-linux@1.5.1 
11:15:09 syncbase amd64-linux@1 
11:15:09 ]]
11:15:09 jiri v23-profile : exit status 2 [[
11:15:09 ERROR: jiri v23-profile: unknown command ""
11:15:09 
11:15:09 Profiles are used to manage external sofware dependencies and offer a balance
11:15:09 between providing no support at all and a full blown package manager. Profiles
11:15:09 can be built natively as well as being cross compiled. A profile is a named
11:15:09 collection of software required for a given system component or application.
11:15:09 Current example profiles include 'syncbase' which consists of the leveldb and
11:15:09 snappy libraries or 'android' which consists of all of the android components
11:15:09 and downloads needed to build android applications. Profiles are built for
11:15:09 specific targets.

https://veyron.corp.google.com/jenkins/job/vanadium-go-race/OS=linux,P=2/1063/console
https://veyron.corp.google.com/jenkins/job/vanadium-signup-group/5644/console

**Comment by ghost** [comment]
@jxson

**Comment by tatatodd** [comment]
I'm seeing these errors too.

I'm not sure whether it affects the actual test though; looking at the logs it seems like it might be annoying to see these errors (and we should fix the problem), but it's not actually causing any tests to fail.

Do you guys agree?  I'm wondering whether this is causing my presubmits to fail, or if the tests are flaky or failing for some other reason.

**Comment by jxson** [comment]
@tatatodd I'm seeing the same thing, the bad exit code being reported (jiri
v23-profile : exit status 2) doesn't effect the result of `jiri test <name>`

**Comment by cosnicolaou** [comment]
The error message implies that portions of the profiles directory are somehow being deleted and/or profiles command are being run to delete profiles. My only theory is that multiple tests are landing on the same machine/root and interfering with each other. This doesn't make sense given that the tests are /not/ failing. I won't be able to get to this until this evening, but the only thing I can suggest to add some debugging output to log the contents of the profiles directory at various points in the tests.

**Comment by tatatodd** [comment]
I didn't look into this closely, but based on the log, it seems like a simple error where we try to run `jiri v23-profile ""` without any command.

I'm blocked on making jiri changes by Cos' big CLs, and on making vom changes by Benj's CLs, so I'll take a look at this now.

**Comment by cosnicolaou** [comment]
On Wed, Nov 18, 2015 at 2:18 PM, Todd Wang notifications@github.com wrote:

> I didn't look into this closely, but based on the log, it seems like a
> simple error where we try to run jiri v23-profile "" without any command.

ok, this one is easy, but is not the problem that Matt reported originally,
I tbr'ed a change last night that causes this and I can fix it trivually,
or you can too. Just look in jiri-test/internal/test/cleanup_profiles.go -
I removed the nacl removal but didn't add a test for the removals string
being empty and then not running jiri v23-profile at all. But this is only
today and is not the problem that led to this bug being filed.

> I'm blocked on making jiri changes by Cos' big CLs,
> 
> sorry:-( I'll check in two of the big ones tonight and the next one
> tomorrow.
> 
> and on making vom changes by Benj's CLs, so I'll take a look at this now.
> 
> see above....

Cheers, Cos.

**Comment by tatatodd** [comment]
Fixed by http://v.io/c/17829

**Comment by jxson** [comment]
Thanks @tatatodd!

**Comment by vr00n** [comment]
This is still happening for me. I tried the clean slate install and then using vanadium-install.sh. 

```
Block 'installBaseProfile' (7/8 in test) of content/installation/step-by-step.md
ERROR: jiri: unknown command "v23-profile"

```
